# Workflow name
name: Frontend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch: null
  
  # Automatic trigger on push events to the main branch
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "frontend/**"
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      
  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  # schedule:
  #   - cron: '0 5 * * 1-5'

# Jobs defined in the workflow
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Run lint
        run: cd frontend && npm run lint

  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Run test
        run: cd frontend && npm test

  build-job:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: "./frontend/package-lock.json"
  # post-build-actions:
  #   needs: [build-and-test-1, build-and-test-2]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Publish test results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: test-results
  #         path: test-results.xml